// 09.react/02.react_staging/16_src向路由组件传递params参数/pages/Home/Message/index.jsx
import React, { Component } from 'react'

import { Link, Route } from 'react-router-dom'

import Detail from './Detail'
export default class Message extends Component {
    state = {
        messageArr: [
            { id: 1, title: 'message01' },
            { id: 2, title: 'message02' },
            { id: 3, title: 'message03' },
        ]
    }
    render() {
        const { messageArr } = this.state
        return (
            <div>
                <ul>
                    {
                        messageArr.map(msg => {
                            return (
                                <li key={msg.id}>
                                    {/* 编写路由链接并且传递params参数的值 */}
                                    <Link to={`/home/message/detail/${msg.id}/${msg.title}`}>{msg.title}</Link>
                                </li>
                            )
                        })
                    }
                </ul>
                <hr />
                {/* 注册路由并且声明params的变量，注意是对应的关系 */}
                <Route path="/home/message/detail/:id/:title" component={Detail}></Route>
            </div>
        )
    }
}

// 10.Vue/04.vue3_vite/03_src_params参数/pages/Message.vue
<template>
  <ul>
    <li v-for="m in messageList">
      <!-- path: `/home/message/detail`, -->
      <router-link
        :to="{
          name: 'detail',
          params: {
            id: m.id,
            title: m.title,
          },
        }"
        :key="m.id"
        >{{ m.title }}</router-link
      >&nbsp;&nbsp;
    </li>
  </ul>
  <hr />
  <router-view></router-view>
</template>

<script>
import { reactive } from "vue";
export default {
  name: "Message",
  setup() {
    const messageList = reactive([
      { id: "001", title: "消息001" },
      { id: "002", title: "消息002" },
      { id: "003", title: "消息003" },
    ]);

    return {
      messageList,
    };
  },
};
</script>

<style>
</style>
