// 10.Vue/02.vue_staging/28_src_路由的params参数/pages/Message.vue
<template>
  <div>
    <ul>
      <li v-for="m in messageList" :key="m.id">
        <!-- 跳转路由并携带query参数，to的字符串写法 -->
        <!-- <router-link :to="`/home/message/detail?id=${m.id}&title=${m.title}`"> -->
        <!-- 跳转路由并携带query参数，to的对象写法 -->
        <!-- <router-link
          :to="{
            name: 'detail',
            query: {
              id: m.id,
              title: m.title,
            },
          }"
        > -->

        <!-- 跳转路由并携带params参数，to的字符串写法 -->
        <!-- <router-link :to="`/home/message/detail/${m.id}/${m.title}`"> -->
        <!-- 跳转路由并携带params参数，to的对象写法，注意不能写path必须写name -->
        <router-link
          :to="{
            name: 'detail',
            params: {
              id: m.id,
              title: m.title,
            },
          }"
        >
          {{ m.title }}
        </router-link>
        &nbsp;&nbsp;
      </li>
    </ul>
    <hr />
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: "Message",
  data() {
    return {
      messageList: [
        { id: "001", title: "消息001" },
        { id: "002", title: "消息002" },
        { id: "003", title: "消息003" },
      ],
    };
  },
};
</script>

<style>
</style>

// 09.react/02.react_staging/16_src向路由组件传递params参数/pages/Home/Message/index.jsx
import React, { Component } from 'react'

import { Link, Route } from 'react-router-dom'

import Detail from './Detail'
export default class Message extends Component {
    state = {
        messageArr: [
            { id: 1, title: 'message01' },
            { id: 2, title: 'message02' },
            { id: 3, title: 'message03' },
        ]
    }
    render() {
        const { messageArr } = this.state
        return (
            <div>
                <ul>
                    {
                        messageArr.map(msg => {
                            return (
                                <li key={msg.id}>
                                    {/* 编写路由链接并且传递params参数的值 */}
                                    <Link to={`/home/message/detail/${msg.id}/${msg.title}`}>{msg.title}</Link>
                                </li>
                            )
                        })
                    }
                </ul>
                <hr />
                {/* 注册路由并且声明params的变量，注意是对应的关系 */}
                <Route path="/home/message/detail/:id/:title" component={Detail}></Route>
            </div>
        )
    }
}
