// 09.react/02.react_staging/08_src_路由的基本使用/App.jsx
import React, { Component } from 'react'
import { Link, Route } from 'react-router-dom'

import Home from './components/Home'
import About from './components/About'


export default class App extends Component {
    render() {
        return (
            <div>
                <div className="row">
                    <div className="col-xs-offset-2 col-xs-8">
                        <div className="page-header"><h2>React Router Demo</h2></div>
                    </div>
                </div>
                <div className="row">
                    <div className="col-xs-2 col-xs-offset-2">
                        <div className="list-group">
                            {/* 原生html中靠a标签跳转不同的页面 */}
                            {/* <a className="list-group-item" href="./about.html">About</a>
                            <a className="list-group-item active" href="./home.html">Home</a> */}

                            {/* 在react中靠路由链接切换组件 -- 编写路由链接 */}
                            <Link className='list-group-item' to="/about">About</Link>
                            <Link className='list-group-item' to="/home">Home</Link>

                        </div>
                    </div>
                    <div className="col-xs-6">
                        <div className="panel">
                            <div className="panel-body">
                                {/* 注册路由 */}
                                <Route path="/home" component={Home} />
                                <Route path="/about" component={About} />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        )
    }
}

// 10.Vue/04.vue3_vite/06_src_vuex不使用组合api/App.vue
<template>
  <div class="row">
    <TopTitle />
  </div>
  <div class="row">
    <div class="col-xs-2 col-xs-offset-2">
      <div class="list-group">
        <router-link class="list-group-item" to="/about" active-class="active"
          >求和案例</router-link
        >
        <router-link class="list-group-item" to="/home" active-class="active"
          >人员信息</router-link
        >
      </div>
    </div>
    <div class="col-xs-6">
      <div class="panel">
        <div class="panel-body re">
          <router-view v-slot="{ Component }">
            <transition name="router">
              <keep-alive>
                <component :is="Component" />
              </keep-alive>
            </transition>
          </router-view>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import TopTitle from "./components/TopTitle.vue";
import "bootstrap/dist/css/bootstrap.min.css";
export default {
  name: "App",
  components: { TopTitle },
};
</script>

<style scoped>
.re {
  position: relative;
}
.router-enter-from,
.router-leave-to {
  transform: translateX(300%);
}
.router-enter-active,
.router-leave-active {
  transition: all 0.5s;
}
.router-enter-to,
.router-leave-from {
  transform: translate(0);
}
</style>
