// 09.react/redux_test/src/containers/Person/index.jsx
import React, { Component } from 'react'
import { nanoid } from 'nanoid'

import { connect } from 'react-redux'
import { addPerson } from '../../redux/actions/person'
class Person extends Component {
    addPerson = () => {
        const { value: name } = this.name
        const { value: age } = this.age
        const personObj = { id: nanoid(), name, age }
        this.props.addPerson(personObj)

    }
    render() {
        return (
            <div>
                <input type="text" ref={c => this.name = c} placeholder='请输入姓名' />
                <input type="text" ref={c => this.age = c} placeholder='请输入年龄' />
                <button onClick={this.addPerson}>添加</button>
                <ul>
                    {
                        this.props.person.map(
                            p => <li key={p.id}>{p.name}---{p.age}</li>
                        )
                    }
                </ul>
            </div>
        )
    }
}

export default connect(
    ({ person }) => ({ person }),
    {
        addPerson
    }
)(Person)

// 10.Vue/02.vue_staging/24_src_求和案例_多组件共享数据/components/Person.vue
<template>
  <div>
    <h1>人员列表</h1>
    <h3 style="color: red">Count组件求和为{{ sum }}</h3>
    <input type="text" placeholder="请输入姓名" v-model="name" />
    <button @click="add">添加</button>
    <ul>
      <li v-for="person in personList" :key="person.id">{{ person.name }}</li>
    </ul>
  </div>
</template>

<script>
import { nanoid } from "nanoid";
import { mapState } from "vuex";
export default {
  name: "Person",
  data() {
    return {
      name: "",
    };
  },
  computed: {
    ...mapState(["personList", "sum"]),
  },
  methods: {
    add() {
      const personObj = { id: nanoid(), name: this.name };
      this.$store.commit("ADD_PERSON", personObj);
      this.name = "";
    },
  },
};
</script>

<style>
</style>
