// 09.react/05.react_router6/src/App.jsx
import React from 'react'

import { NavLink } from 'react-router-dom'
import Header from './components/Header'

import element from './routes'

export default function App() {
    // 路由表
    // const element = useRoutes(routes)

    return (
        <div>
            <div className="row">
                <Header />
            </div>
            <div className="row">
                <div className="col-xs-2 col-xs-offset-2">
                    <div className="list-group">
                        {/* 路由链接 */}
                        <NavLink className={'list-group-item'} to={'/about'}>About</NavLink>
                        <NavLink className={'list-group-item'} to={'/home'}>Home</NavLink>
                    </div>
                </div>
                <div className="col-xs-6">
                    <div className="panel">
                        <div className="panel-body">
                            {/* useRoutes 使用路由表快速生成并且集中管理 */}
                            {element()}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

// 10.Vue/02.vue_staging/26_src_路由基本使用和嵌套路由/App.vue
<template>
  <div>
    <div class="row">
      <Banner />
    </div>
    <div class="row">
      <div class="col-xs-2 col-xs-offset-2">
        <div class="list-group">
          <router-link class="list-group-item" active-class="active" to="/about"
            >About</router-link
          >
          <router-link class="list-group-item" active-class="active" to="/home"
            >Home</router-link
          >
        </div>
      </div>
      <div class="col-xs-6">
        <div class="panel">
          <div class="panel-body">
            <router-view></router-view>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Banner from "./components/Banner.vue";
import "bootstrap/dist/css/bootstrap.css";
export default {
  name: "App",
  components: { Banner },
};
</script>

<style>
</style>
