// 09.react/redux_test/src/components/Count/index.jsx
import React, { Component } from 'react'

export default class Count extends Component {
    increment = () => {
        const { value } = this.selectNumber
    }
    decrement = () => {
        const { value } = this.selectNumber
    }
    incrementIfOdd = () => {
        const { value } = this.selectNumber

    }
    incrementAsync = () => {
        const { value } = this.selectNumber


    }
    render() {
        return (
            <div>
                <h2>当前求和为:???</h2>
                <select ref={c => this.selectNumber = c}>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                </select>
                <button onClick={this.increment}>+</button>
                <button onClick={this.decrement}>-</button>
                <button onClick={this.incrementIfOdd}>当前是奇数再加</button>
                <button onClick={this.incrementAsync}>异步加</button>
            </div>
        )
    }
}

// 10.Vue/02.vue_staging/22_src_求和案例_纯vue版/components/Count.vue
<template>
  <div>
    <h1>当前求和为:{{ sum }}</h1>
    <select v-model.number="n">
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
    </select>
    <button @click="increment">+</button>
    <button @click="decrement">-</button>
    <button @click="incrementOdd">当前求和为奇数再加</button>
    <button @click="incrementWait">等一等再加</button>
  </div>
</template>

<script>
export default {
  name: "Count",
  data() {
    return {
      sum: 0,
      n: 1,
    };
  },
  methods: {
    increment() {
      this.sum += this.n;
    },
    decrement() {
      this.sum -= this.n;
    },
    incrementOdd() {
      if (this.sum % 2) {
        this.sum += this.n;
      }
    },
    incrementWait() {
      setTimeout(() => {
        this.sum += this.n;
      }, 1000);
    },
  },
};
</script>

<style scoped>
button {
  margin: 5px;
}
</style>
