// 10.Vue/02.vue_staging/30_src_编程式路由导航和缓存路由组件/pages/Message.vue
<template>
  <div>
    <ul>
      <li v-for="m in messageList" :key="m.id">
        <!-- 跳转路由并携带query参数，to的字符串写法 -->
        <!-- <router-link :to="`/home/message/detail?id=${m.id}&title=${m.title}`"> -->
        <!-- 跳转路由并携带query参数，to的对象写法 -->
        <router-link
          :to="{
            name: 'detail',
            query: {
              id: m.id,
              title: m.title,
            },
          }"
        >
          <!-- 跳转路由并携带params参数，to的字符串写法 -->
          <!-- <router-link :to="`/home/message/detail/${m.id}/${m.title}`"> -->
          <!-- 跳转路由并携带params参数，to的对象写法，注意不能写path必须写name -->
          <!-- <router-link
          :to="{
            name: 'detail',
            params: {
              id: m.id,
              title: m.title,
            },
          }"
        > -->
          {{ m.title }}
        </router-link>
        <button @click="pushShow(m)">push查看</button>
        <button @click="replaceShow(m)">replace查看</button>
        &nbsp;&nbsp;
      </li>
    </ul>
    <hr />
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: "Message",
  data() {
    return {
      messageList: [
        { id: "001", title: "消息001" },
        { id: "002", title: "消息002" },
        { id: "003", title: "消息003" },
      ],
    };
  },
  beforeDestroy() {
    console.log("Message组件即将被销毁");
  },
  methods: {
    pushShow(m) {
      //   console.log(this.$router);
      //   编程式导航
      this.$router.push({
        name: "detail",
        query: {
          id: m.id,
          title: m.title,
        },
      });
    },
    replaceShow(m) {
      this.$router.replace({
        name: "detail",
        query: {
          id: m.id,
          title: m.title,
        },
      });
    },
  },
};
</script>

<style>
</style>

// 09.react/02.react_staging/20_src_编程式路由导航/pages/Home/Message/index.jsx
import React, { Component } from 'react'

import { Link, Route } from 'react-router-dom'

import Detail from './Detail'
export default class Message extends Component {
    state = {
        messageArr: [
            { id: 1, title: 'message01' },
            { id: 2, title: 'message02' },
            { id: 3, title: 'message03' },
        ]
    }

    replaceShow = (id, title) => {
        // 编程式实现replace跳转+携带params参数
        // this.props.history.replace(`/home/message/detail/${id}/${title}`)

        // replace跳转实现query参数
        // this.props.history.replace(`/home/message/detail?id=${id}&title=${title}`)

        // replace跳转实现state参数
        this.props.history.replace(`/home/message/detail`, { id, title })


    }
    pushShow = (id, title) => {
        // 编程式实现push跳转+携带params参数
        // this.props.history.push(`/home/message/detail/${id}/${title}`)

        // push跳转实现query参数
        // this.props.history.push(`/home/message/detail?id=${id}&title=${title}`)

        // push跳转实现state参数
        this.props.history.push(`/home/message/detail`, { id, title })

    }

    back = () => {
        this.props.history.goBack()
    }
    forWard = () => {
        this.props.history.goForward()
    }
    go = () => {
        this.props.history.go(-2)
    }
    render() {
        const { messageArr } = this.state
        return (
            <div>
                <ul>
                    {
                        messageArr.map(msg => {
                            return (
                                <li key={msg.id}>
                                    {/* 编写路由链接并且传递state参数(注意这个state就是个属性，根组件的state没有任何关系) */}
                                    <Link to={{
                                        pathname: `/home/message/detail`,
                                        state: {
                                            id: msg.id,
                                            title: msg.title
                                        }
                                    }}>{msg.title}</Link>
                                    &nbsp;<button onClick={() => this.pushShow(msg.id, msg.title)}>push查看</button>
                                    &nbsp;<button onClick={() => this.replaceShow(msg.id, msg.title)}>replace查看</button>
                                </li>
                            )
                        })
                    }
                </ul>
                <hr />
                {/* <Route path="/home/message/detail/:id/:title" component={Detail}></Route> */}
                <Route path="/home/message/detail" component={Detail}></Route>
                <button onClick={this.back}>回退</button>
                <button onClick={this.forWard}>前进</button>
                <button onClick={this.go}>go</button>
            </div>
        )
    }
}
