// 10.Vue/02.vue_staging/27_src_路由的query参数和命名路由/pages/Message.vue
<template>
  <div>
    <ul>
      <li v-for="m in messageList" :key="m.id">
        <!-- 跳转路由并携带query参数，to的字符串写法 -->
        <!-- <router-link :to="`/home/message/detail?id=${m.id}&title=${m.title}`"> -->
        <!-- 跳转路由并携带query参数，to的对象写法 -->
        <router-link
          :to="{
            name: 'detail',
            query: {
              id: m.id,
              title: m.title,
            },
          }"
        >
          {{ m.title }}
        </router-link>
        &nbsp;&nbsp;
      </li>
    </ul>
    <hr />
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: "Message",
  data() {
    return {
      messageList: [
        { id: "001", title: "消息001" },
        { id: "002", title: "消息002" },
        { id: "003", title: "消息003" },
      ],
    };
  },
};
</script>

<style>
</style>

// 09.react/05.react_router6/05_src_嵌套路由和路由的params参数/pages/Message.jsx
import React, { useState } from 'react'
import { Link, Outlet } from 'react-router-dom'

export default function Message() {
    const [messages] = useState([
        { id: '001', title: '消息1', content: '你好' },
        { id: '002', title: '消息2', content: '我不好' },
        { id: '003', title: '消息3', content: '不，你好得很' },
    ])
    return (
        <div>
            <ul>
                {
                    // 生成路由链接
                    messages.map(message => (
                        <li key={message.id}>
                            <Link to={`detail/${message.id}/${message.title}/${message.content}`}>{message.title}</Link>
                        </li>
                    ))
                }
            </ul>
            <hr />
            <Outlet />
        </div>
    )
}
