// 10.Vue/04.vue3_vite/02_src_嵌套路由和query参数/pages/Message.vue
<template>
  <ul>
    <li v-for="m in messageList">
      <!-- path: `/home/message/detail`, -->
      <router-link
        :to="{
          name: 'detail',
          query: {
            id: m.id,
            title: m.title,
          },
        }"
        :key="m.id"
        >{{ m.title }}</router-link
      >&nbsp;&nbsp;
    </li>
  </ul>
  <hr />
  <router-view></router-view>
</template>

<script>
import { reactive } from "vue";
export default {
  name: "Message",
  setup() {
    const messageList = reactive([
      { id: "001", title: "消息001" },
      { id: "002", title: "消息002" },
      { id: "003", title: "消息003" },
    ]);

    return {
      messageList,
    };
  },
};
</script>

<style>
</style>

// 09.react/05.react_router6/05_src_嵌套路由和路由的params参数/pages/Message.jsx
import React, { useState } from 'react'
import { Link, Outlet } from 'react-router-dom'

export default function Message() {
    const [messages] = useState([
        { id: '001', title: '消息1', content: '你好' },
        { id: '002', title: '消息2', content: '我不好' },
        { id: '003', title: '消息3', content: '不，你好得很' },
    ])
    return (
        <div>
            <ul>
                {
                    // 生成路由链接
                    messages.map(message => (
                        <li key={message.id}>
                            <Link to={`detail/${message.id}/${message.title}/${message.content}`}>{message.title}</Link>
                        </li>
                    ))
                }
            </ul>
            <hr />
            <Outlet />
        </div>
    )
}
