// 09.react/02.react_staging/05_src_github搜索案例axios/components/Search/index.jsx
import React, { Component } from 'react'

import axios from 'axios'

export default class Search extends Component {
    search = async () => {
        // 获取用户的输入，连续解构赋值+重命名
        const { keyWordElement: { value: keyWord } } = this
        if (!keyWord.trim()) return alert('请输入内容')
        // 发送请求前通知App更新状态
        this.props.updateAppState({ isFirst: false, isLoading: true })
        try {
            // 发送网络请求
            const res = await axios({
                method: 'GET',
                url: '/api1/search/users',
                params: {
                    q: keyWord
                }
            })
            // console.log(res.data);
            this.props.updateAppState({ isLoading: false, items: res.data.items })

        } catch (err) {
            // 请求失败后通知App更新状态
            this.props.updateAppState({ isLoading: false, err: err.message })
        }
    }
    search2 = (e) => {
        if (e.keyCode === 13) {
            this.search()
            this.keyWordElement.value = ''
            // this.keyWordElement.attributes.placeholder.value = '继续'
        }
    }
    render() {
        return (
            <section className="jumbotron">
                <h3 className="jumbotron-heading">Search Github Users</h3>
                <div>
                    <input autoFocus={true} onKeyUp={this.search2} ref={c => this.keyWordElement = c} type="text" placeholder="enter the name you search" />&nbsp;
                    <div onClick={this.search} className="btn btn-success">Search</div>
                </div>
            </section>
        )
    }
}

// 10.Vue/02.vue_staging/17_src_github搜索案例/components/Search.vue
<template>
  <section class="jumbotron">
    <h3 class="jumbotron-heading">Search Github Users</h3>
    <div>
      <input
        type="text"
        placeholder="enter the name you search"
        v-model="keyWord"
        @keydown.enter="searchUsers"
      />&nbsp;
      <button @click="searchUsers">Search</button>
    </div>
  </section>
</template>

<script>
import axios from "axios";
export default {
  name: "Search",
  data() {
    return {
      keyWord: "",
    };
  },
  methods: {
    searchUsers() {
      if (!this.keyWord.trim()) return alert("请输入");
      this.$bus.$emit("updateListData", {
        isFirst: false,
        isLoading: true,
        errMsg: "",
        users: [],
      });

      axios.get(`https://api.github.com/search/users?q=${this.keyWord}`).then(
        (res) => {
          // 请求成功后
          this.$bus.$emit("updateListData", {
            isLoading: false,
            errMsg: "",
            users: res.data.items,
          });
        },
        (err) => {
          // 请求失败后
          this.$bus.$emit("updateListData", {
            isLoading: false,
            errMsg: err.message,
            users: [],
          });
        }
      );
    },
  },
};
</script>

<style>
</style>
